package Acme::CPANLists::Import::RSAVAGE::ArrayAndSetOperations;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in the article [http://savage.net.au/Perl-modules/html/setops.report.html] (retrieved on 2016-02-21). For the full article, visit the URL.",entries=>[{module=>"Array::AsObject"},{module=>"Array::Compare"},{module=>"Array::Uniq"},{module=>"Array::Utils"},{module=>"Benchmark::Featureset::SetOps"},{module=>"Bit::Vector"},{module=>"EO::Array"},{module=>"Object::Array"},{module=>"Set::Array"},{module=>"Set::Bag"},{module=>"Set::DynamicGroups"},{module=>"Set::Groups"},{module=>"Set::Hash"},{module=>"Set::Light"},{module=>"Set::NestedGroups"},{module=>"Set::Object"},{module=>"Set::Relation"},{module=>"Set::Scalar"},{module=>"Set::SortedArray"},{module=>"Set::Tiny"},{module=>"Set::Toolkit"}],summary=>"CPAN modules which offer array and set operations (2012)"});

1;
# ABSTRACT: CPAN modules which offer array and set operations (2012)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in the article L<http://savage.net.au/Perl-modules/html/setops.report.html> (retrieved on 2016-02-21). For the full article, visit the URL.

