package Acme::CPANLists::Import::RSAVAGE::ClassesRolesWithMooAndMoos;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in the article [http://savage.net.au/Module-reviews/html/gci.2012.url.mapper.modules.html] (retrieved on 2016-02-21). For the full article, visit the URL.",entries=>[{module=>"CGI::Application::Plugin::ActionDispatch"},{module=>"CGI::Application::Plugin::REST"},{module=>"CGI::Application::Plugin::Routes"},{module=>"CGI::Application::URIMapping"},{module=>"CGI::Easy::URLconf"},{module=>"Catalyst::Dispatcher"},{module=>"Dancer::Plugin::Dispatcher"},{module=>"Dancer::Route"},{module=>"Forward::Routes"},{module=>"HTTP::Router::Route"},{module=>"Jifty::Dispatcher"},{module=>"Mojo::Base"},{module=>"Mojolicious::Routes"},{module=>"Path::Dispatcher"},{module=>"Path::Extended"},{module=>"Path::Router"},{module=>"Pickles::Dispatcher"},{module=>"Pinwheel::Mapper"},{module=>"Plack::App::Path::Router"},{module=>"Plack::App::Path::Router::PSGI"},{module=>"Plack::App::URLMap"},{module=>"Plack::Util::Accessor"},{module=>"PlackX::RouteBuilder"},{module=>"REST::Application::Routes"},{module=>"Router::Dumb"},{module=>"Router::Generic"},{module=>"Router::Simple"},{module=>"Routes::Tiny"},{module=>"Scaffold::Routes"},{module=>"Silki::Action::REST"},{module=>"Sleep::Routes"},{module=>"Web::API::Mapper"},{module=>"Web::Dispatcher::Simple"},{module=>"Web::Simple"}],summary=>"Classes and Roles with Moo and Moos (2012)"});

1;
# ABSTRACT: Classes and Roles with Moo and Moos (2012)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in the article L<http://savage.net.au/Module-reviews/html/gci.2012.url.mapper.modules.html> (retrieved on 2016-02-21). For the full article, visit the URL.

