package Acme::CPANLists::Import::RSAVAGE::CountrySubcountryCodes;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in the article [http://savage.net.au/Perl-modules/html/locale.report.html] (retrieved on 2016-02-21). For the full article, visit the URL.",entries=>[{module=>"Business::Cart::Generic"},{module=>"Locale::Codes"},{module=>"Locale::Country::Multilingual"},{module=>"Locale::Geocode"},{module=>"Locale::Object"},{module=>"Locale::SubCountry"},{module=>"WWW::Scraper::Wikipedia::ISO3166"}],summary=>"CPAN modules which offer country and sub-country codes (2012)"});

1;
# ABSTRACT: CPAN modules which offer country and sub-country codes (2012)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in the article L<http://savage.net.au/Perl-modules/html/locale.report.html> (retrieved on 2016-02-21). For the full article, visit the URL.

