package Acme::CPANLists::Import::RSAVAGE::StopWordLists;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in the article [http://savage.net.au/Perl-modules/html/stopwordlists.report.html] (retrieved on 2016-02-21). For the full article, visit the URL.",entries=>[{module=>"AI::Categorizer"},{module=>"Benchmark::Featureset::StopWordLists"},{module=>"Blog::Spam"},{module=>"DBIx::FullTextSearch"},{module=>"DBIx::TextIndex"},{module=>"Elastic::Model"},{module=>"HTML::Index"},{module=>"Image::WordCloud"},{module=>"KinoSearch"},{module=>"KinoSearch1"},{module=>"Lingua::EN::Segmenter"},{module=>"Lingua::EN::StopWordList"},{module=>"Lingua::StopWords"},{module=>"Lucy"},{module=>"Perl::Critic"},{module=>"Pod::Spell"},{module=>"Pod::Weaver"},{module=>"Search::Glimpse"},{module=>"Search::Indexer::Incremental::MD5"},{module=>"Search::Tokenizer"},{module=>"Search::Tools"},{module=>"Test::Spelling"},{module=>"Text::DeDuper"},{module=>"Text::Language::Guess"},{module=>"Text::Similarity"},{module=>"UMLS::SenseRelate"},{module=>"WAIT"},{module=>"WordNet::Similarity"},{module=>"combine"}],summary=>"CPAN modules which offer stopword lists (2015)"});

1;
# ABSTRACT: CPAN modules which offer stopword lists (2015)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in the article L<http://savage.net.au/Perl-modules/html/stopwordlists.report.html> (retrieved on 2016-02-21). For the full article, visit the URL.

