package Acme::CPANLists::Import::RSAVAGE::XML_2006;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in the article [http://savage.net.au/Ron/html/XML-ramble.html] (retrieved on 2016-02-21). For the full article, visit the URL.",entries=>[{module=>"XML::DOM"},{module=>"XML::Parser"},{module=>"XML::SAX"},{module=>"XML::SAX::Base"},{module=>"XML::XPath"},{module=>"XML::XPath::Boolean"},{module=>"XML::XPath::Literal"},{module=>"XML::XPath::NodeSet"},{module=>"XML::XPath::Number"}],summary=>"CPAN modules for XML processing (2006)"});

1;
# ABSTRACT: CPAN modules for XML processing (2006)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in the article L<http://savage.net.au/Ron/html/XML-ramble.html> (retrieved on 2016-02-21). For the full article, visit the URL.

